### ISSUE TITLE
Flash data is dicarded after static file requests when using the development server

### ISSUE THREAD

**Issue by jeremyongithub** [danielfm/django-flash#1]
When using the development server in django, the static files requests are processed with django.
Therefore the following request after saving a value in the flashscope object is likely to be  a static file request (a CSS/ an image file). It seems that the flash data is discarded at that time.

While this should not happen in production, it prevents the application to run with the development server.

Is there a way for django-flash not to remove the data when processing these requests?

Python 2.5 /2.6
Django 1.1 RC
django-flash 1.5.2

**Comment by danielfm** [comment]
As far as I know there's no way to distinguish those requests. However, I can create a new setting in django-flash where you specify one or more URL patterns that should not trigger the flashscope update, therefore keeping values intact. Or something like that.

I'll study the best solution to that issue and hopefully release a fix in the next few days.

**Comment by jeremyongithub** [comment]
You can either rejects every request that ends with _._ or all that starts with the MEDIA_URL variable defined in settings.py

So I patched the middleware.py accordingly (so I don't have to install an apache for development):

```
21,24d20
< from django.conf import settings
< 
< import re
< 
57,60c53
<         #We don't want requests for static files taken into account
<         pattern = "^%s" % settings.MEDIA_URL
<         if not re.match(pattern, request.path):
<             flash.update()
---
>         flash.update()
```

I haven't tested what would happen is MEDIA_URL is empty though.

**Comment by danielfm** [comment]
Thanks for the report and patch!

Your approach looks fine, but I think the best way to go in this situation is to detect whether the current URL resolves to 'django.views.static.serve'. This should give you enough freedom to configure your MEDIA settings and URLs the way you want without getting in the way.

Anyway, I'll do some testing and when get something done I'll let you know!

**Comment by danielfm** [comment]
Okay, the fix is available at the repository. Check it out to see if it works before I close this issue and release the new version officially.

Thanks!

**Comment by jeremyongithub** [comment]
Yep, works like a charm.

Thanks for being so responsive :)
