### ISSUE TITLE
FLASH_IGNORE_MEDIA doesn't seem sufficient if you need to have static content served via multiple different apps

### ISSUE THREAD

**Issue by timmfin** [danielfm/django-flash#2]
I'd love to use django-flash but it looks like I would have troubles in its current form.

I have a django project that has three different apps in it (let's say project1, project2, and project3). Since the same domain will serve all three projects and other non-django applications I need to use urls like /project1/c/styles.css , /project2/j/somejavascript.js , and /project3/i/blank.gif for static js, css, and images. In development mode I'm using django.views.static.serve to get those above urls to point to the static-www/ directory in our source (eg ./static-www/project1/c/styes.css). 

From [the documentation](http://djangoflash.destaquenet.com/configuration.html#django-flash-and-requests-to-media-files) it looks like this is a problem. In production flash will work fine, but in development static file requests will flush the flash. 

I see that you've made FLASH_IGNORE_MEDIA, but it won't suit this case because I have 3 different static url prefixes so [checking a single MEDIA_URL](http://github.com/danielfm/django-flash/blob/e1239a1f6de75485d5e2152ec2554f5a07968c02/src/djangoflash/middleware.py#L51) won't work. 

Maybe and additional setting that is a regular expression? Or an array of several strings? 

I might just code this up myself (seems pretty straightforward) but wanted to ask you first just in case I was missing something.

**Comment by timmfin** [comment]
Or maybe it would be better to check if the request resolves to django.views.static.serve OR if a (non-empty) MEDIA_URL is prefixes the url?

([noticed in this patch](http://github.com/danielfm/django-flash/commit/52045f8ceea7c0b5fa111aca3bc6a9394c2b282e))

**Comment by danielfm** [comment]
Yes, a more decent solution would be to check if the URL resolves to 'django.views.static.serve'. In fact, I already tried that approach (as you pointed out) and it works fine, but it's much, much slower than the current solution. This, of course, shouldn't be a problem during development.

I will probably merge that old middleware with the new FLASH_IGNORE_MEDIA setting, so you can get Django-Flash working with 'django.views.static.serve' and, at the same time, avoid unnecessary calls to Django's dog-slow URL resolver in production.

What do you think?

**Comment by timmfin** [comment]
Sounds good to me. I might hack something up for right now, but it will be nice if I can tell our devs on the team to just install the "offical" django-flash after you've committed the change.

Maybe if I'm motivated I'll do a fork and send a pull request :)

**Comment by danielfm** [comment]
It's easy to change this, but I also have to update the tests and the documentation, so it will take some time. The new version should be out by tomorrow.

**Comment by danielfm** [comment]
Ok, new version released! Give it a try and let me know if it works for you.

**Comment by timmfin** [comment]
Yup, it works. And your version that one keeps the one setting instead of adding one is probably better. Thanks!

**Comment by danielfm** [comment]
Great! I'm closing this issue then.
Thanks.
