### ISSUE TITLE
AssertionError: The session-based flash storage requires session middleware to be installed.

### ISSUE THREAD

**Issue by pats** [danielfm/django-flash#3]
Hi,

when i try something like http://domain/admin then i get:

Traceback (most recent call last):

  File "/usr/lib/python2.5/site-packages/django/core/servers/basehttp.py", line 279, in run
    self.result = application(self.environ, self.start_response)

  File "/usr/lib/python2.5/site-packages/django/core/servers/basehttp.py", line 651, in **call**
    return self.application(environ, start_response)

  File "/usr/lib/python2.5/site-packages/django/core/handlers/wsgi.py", line 245, in **call**
    response = middleware_method(request, response)

  File "/usr/lib/python2.5/site-packages/django_flash-1.6.1-py2.5.egg/djangoflash/middleware.py", line 77, in process_response
    storage.set(self._get_flash_from_request(request), request, response)

  File "/usr/lib/python2.5/site-packages/django_flash-1.6.1-py2.5.egg/djangoflash/storage/session.py", line 33, in set
    assert hasattr(request, 'session'), "The session-based flash storage " \

AssertionError: The session-based flash storage requires session middleware to be installed.

Important is that url doesn't have slash at the end, with slash works well.

My settings looks ok, djangoflash.middleware.FlashMiddleware is after session middleware.

**Comment by danielfm** [comment]
Hey,

I did a few tests with a project here and I couldn't reproduce the problem. Can you please send me a Django project that reproduces that issue?

**Comment by rob-b** [comment]
The issue is caused when CommonMiddleware is called before SessionMiddleware. If APPEND_SLASH is True, which it is by default, then CommonMiddleware will return a 301 before SessionMiddleware has a chance to add the session attribute to request.

FlashMiddleware.process_response then calls storage.set which raises the exception because it recieves a request with no session attribute. The easiest way to solve this is just make sure that the sessionmiddleware is first in the settings.py

**Comment by danielfm** [comment]
Indeed, the easiest way to solve this would be to place the SessionMiddleware _before_ in the middleware chain.

But the right way to solve this, IMO, would be to redirect to the correct URL (e.g. using reverse()). The CommonMiddleware always appears _before_ the SessionMiddleware in the Django docs, so I think it's better to keep it that way.

**Comment by rob-b** [comment]
I don't follow, where would you you redirect using reverse()?

**Comment by danielfm** [comment]
For example, let's suppose you have a contact form in your app:

```
def index(request):
    # Displays the home page
    pass

def contact(request):
    contact_request_form = None

    # Was a contact request submitted?
    if request.method == 'POST':
        contact_request_form = ContactRequestForm(request.POST)

        # Is form valid?
        if contact_request_form.is_valid():
            contact_request_form.save()
            request.flash['notification_info'] = _('Your message was sent successfully.')

            # Redirect to the 'index' view
            return HttpResponseRedirect(reverse(index))
        else:
            request.flash.now['notification_error'] = _('Please re-check the invalid fields and try again.')
    else:
        # Only displaying the contact page
        contact_request_form = ContactRequestForm()

    return render_to_response('contact/form.html', locals(), context_instance=RequestContext(request))
```

It's a good practice to use `reverse()` instead of hardcode URLs in views and templates. Please check out the [Django docs](http://docs.djangoproject.com/en/dev/topics/http/urls/#django.core.urlresolvers.reverse) for more info.

**Comment by rob-b** [comment]
Sure, I understand all of that and I never hardcode urls. What I don't understand is how it solves the issue created by CommonMiddleware returning a redirect before SessionMiddleware has attached the session which in turn causes FlashMiddleware to throw an AssertionError

**Comment by danielfm** [comment]
In Django-Flash, I just followed a convention adopted by several other session-based middlewares: don't assume the session is available; if it's not, raise an AssertionError.

In fact, I think this is a problem with Django itself, because if only a few middlewares get executed during the request phase, why execute the _whole_ middleware chain during the response phase? :S

Anyway... I guess there's nothing I can do to fix this.

**Comment by pats** [comment]
@rob-b you are right. CommonMiddleware must be before SessionMiddleware. Many thanks for this tip.

@danielfm thanks for info. Maybe add some more information in docs?

**Comment by danielfm** [comment]
Sure, I'm on it! :)

**Comment by miracle2k** [comment]
Without being too familiar with the code so far, isn't it possible to somehow skip those 301 redirects? For example, if flash was set at all by the view...?
