### ISSUE TITLE
Untitled

### ISSUE THREAD

**Issue by mathewbyrne** [danielfm/django-flash#4]
I'm new to Django, so I'm not sure if this is the case or not, but I found following the configuration instructions in the documentation overwrote the default Context Processors. So after I'd installed Django Flash a bunch of template variables suddenly disappeared.

I found this was the easiest way to add the django-flash context processor to the defaults:

```
from django.conf import global_settings
TEMPLATE_CONTEXT_PROCESSORS = global_settings.TEMPLATE_CONTEXT_PROCESSORS + (
    'djangoflash.context_processors.flash',
)
```

I'm not sure if this is Django best-practise, but potentially it should also be mentioned in the documentation?

**Comment by danielfm** [comment]
I think it's better not to rely on the global settings in this case. For example, not every Django project needs to use the i18n or auth stuff, and yet they are included in the default TEMPLATE_CONTEXT_PROCESSORS.
