### ISSUE TITLE
flash.now.add method

### ISSUE THREAD

**Issue by chy-causer** [danielfm/django-flash#6]
Hi,

It would be awesome if the flash.now object had a now method similar to flash.now. I appreciate it may run into problems if you add to the list using both now and "not now" so I haven't created a patch for it just yet. I was just wondering what people thought about this kind of functionality and if it's a non-starter or not.

Many thanks
Chris

**Comment by danielfm** [comment]
Hey!

I don't think I'm following. Can you give me an example where such a feature would be useful?

**Comment by chy-causer** [comment]
Hi Daniel,

Apologies that I didn't make myself clear. This is what I am doing at the moment:

```
request.flash.add('warning', 'hello world 1' )
request.flash.add('warning', 'hello again' )
request.flash._update_status('warning')
```

whereas a one liner would be:

```
request.flash.now.add('warning', 'hello world1')
```

obviously, with more warnings elsewhere. Again, the problem would be if I subsequently did 

```
request.flash.add( 'warning', 'ooops')
```

I don't know what would happen in this instance. Would it display both in the next request, or just the one which wasn't instantiated via the now object.

Thanks for the quick reply!

**Comment by danielfm** [comment]
Of course! I think it would be a useful addition to the API. Now, regarding implementation...

At this point, if you `add` a value previously set with `now`, this is what happens:

```
request.flash.now["key"] = "value" # expires at the end of the CURRENT request
request.flash.add("key", "another value") # ooops, not anymore!
```

In this example, `flash["key"]` (and its values, of course) _won't be removed at the end of the current request_. In summary, the last update wins.

I'm not saying that this is the way it should be, but so far I've heard no complaints. So I have no problems in make things work similarly the other way around:

```
request.flash["key"] = "value" # expires at the end of the NEXT request
request.flash.now.add("key", "another value") # ooops, not anymore!
```

Of course, if you want to be sure that a value will make it to the next request, just call `request.flash.keep("key")`. Or call `request.flash.discard("key")` if you want it _not_ to make it to the next request. More details on the [API documentation](http://djangoflash.destaquenet.com/modules/models.html).

What do you think?

**Comment by chy-causer** [comment]
I think that's the best way to do things.

Would you like me to submit a patch, or are you happy to do this yourself? 

BTW, thanks for the brilliant django-app. I use it all the time!

**Comment by danielfm** [comment]
Thanks! :-) No need to bother. I'll let you know when it's ready so you can give it a try.

**Comment by danielfm** [comment]
Okay, changes pushed to master. Things are working the way I described earlier, with a few considerations.

Now, both methods `request.flash.add()` and `request.flash.now.add()` work with several values. So this will work as expected:

```
request.flash.add("key", "value 1", "value 2")
request.flash.now.add("key", "value 1", "value 2")
```

All changes are listed in `doc/source/changelog.rst`. Please give it a try and tell me what you think.

**Comment by chy-causer** [comment]
Looks good :)

Slight problem that the changelog doesn't look like it's been parsed and it's giving me error messages when viewed through the github web interface.

**Comment by danielfm** [comment]
So take a look at this [compare view](http://github.com/danielfm/django-flash/compare/657685ac...80a614c1).

**Comment by chy-causer** [comment]
Thanks for that. I was just wondering why it doesn't eg give a date for version 1.7.1 unlike the other versions.

**Comment by danielfm** [comment]
Because I don't know exactly when I will be able to release that new version. :) Probably this weekend.

**Comment by chy-causer** [comment]
Ah, I see :)
