### ISSUE TITLE
bad source tarball for 1.8 release

### ISSUE THREAD

**Issue by 3point2** [danielfm/django-flash#8]
it looks like the source tarball for the 1.8 release is missing a required ez_setup.py file.

running 'pip install django-flash' results in "ImportError: No module named ez_setup" when running setup.py.

the 1.7 release works fine. this is the difference in the contents of the top level of the two tarballs:

django-flash-1.7:
AUTHORS  PKG-INFO  doc/         fabfile.py  setup.py
LICENSE  README    ez_setup.py  setup.cfg   src/

django-flash-1.8:
PKG-INFO  setup.cfg  setup.py  src/

**Comment by danielfm** [comment]
I don't know, I think there's something weird happening on PyPI; even though I upload a correct tarball (thanks to setuptools-git), it ends up with bunch of missing files.

Do you have any idea of what's causing this?

**Comment by 3point2** [comment]
i have no idea. it seems unlikely to me that PyPi is modifying your tarball after you upload it. have you untarred the tarball produced by setuptools to check that everything is there? the only thing I can think of is that you might need a manifest file to include the files that are being left out: see http://docs.python.org/release/2.6.6/distutils/sourcedist.html#manifest .

**Comment by danielfm** [comment]
I think it's ok now. Give it a try.

**Comment by 3point2** [comment]
yes, it seems to be working now. thanks!
